Feat/jsj/qyog 26
modern-agile-team/dongurami-front-v2 pull request #39
Opened 2023-12-16 07:04 UTC by jsj1510

# Pull Request

## 티켓

티켓명과 url은 수정해주세요.

[QYOG-26][(https://dongurami.atlassian.net/browse/QYOG-26)]

## 작업 내용

- 자유, 공지게시판 조회
- 자유, 공지게시판 삭제
- 생성, 수정 페이지 UI

## 스크린샷

- 스크린샷

## 테스트

- 작성한 테스트에 대한 설명

## 기타

- 커밋명 잘못정한것들도 꽤 있는거 같은데 피드백해주세요
- 자유, 공지 게시판 한번에 같은페이지에서 다루려고 시도는 해보고있는데 잘안되네요
피드백이 필요합니다,
제가 겪는 문제점은 두 게시판 키값이 달라 어떻게 해야할지 어렵네요
ex) 자유는  freePost인데 공지는 noticePost

2023-12-17 05:20 UTC, soonki-98 requested changes

2023-12-17 05:39 UTC, soonki-98 commented on src/containers/Board/DetailBoard/DetailBoard.tsx
> +  }, []);
```suggestion
```
useMutaion 대신에 useQuery를 사용하면 이 코드는 필요없어요

2023-12-17 05:39 UTC, soonki-98 commented on src/containers/Board/DetailBoard/DetailBoard.tsx
> +  });
```suggestion
  const { data } = useQuery({
    queryFn: async () => {
      // const response = await checkApi('get', router.query.type as string);
      const response = await boardsAPI.freePost.getPost({
        freePostId: Number(postId),
      });

      // const response = await boardsAPI.noticePost.getPost({
      //   noticePostId: Number(postId),
      // });

      return response;
    },
    queryKey: ["post", postId],
    enabled: postId !== undefined
  });
```

이건 페이지 입장했을때 데이터를 바로 가져와야 하기 때문에 useMutaion보다는 useQuery가 더 적절해보이네요

2023-12-17 05:39 UTC, soonki-98 commented on src/containers/Board/DetailBoard/DetailBoard.tsx
> +  );
```suggestion
```
useQuery쓰면 이것도 필요없어져요

2023-12-17 05:39 UTC, soonki-98 commented on src/containers/Board/DetailBoard/DetailBoard.tsx
> +      <S.Title>{post?.freePost.title}</S.Title>
```suggestion
      <S.Title>{data?.freePost.title}</S.Title>
```

2023-12-17 05:39 UTC, soonki-98 commented on src/containers/Board/DetailBoard/DetailBoard.tsx
> +          <S.Title>{post?.freePost.description}</S.Title>
```suggestion
          <S.Title>{data?.freePost.description}</S.Title>
```

2023-12-17 05:39 UTC, soonki-98 commented on src/containers/Board/DetailBoard/emotion.ts
> +`;
```suggestion
export const WrapBar = styled(Row)`
  padding: 12px 20px;
  flex-direction: row;
  /* align-items: center; */
  display: flex;
  justify-content: flex-end;
`;
```
flex display 사용하기 편하려고 Row와 Column이라는 컴포넌트 만들어놨어요 참고해주시면 좋을거같아요

2023-12-17 05:41 UTC, soonki-98 commented on src/containers/Board/WriteBoard/WriteBoard.tsx
> +  });
이 부분도 useMutation 사용하는것보다는 useQuery 사용이 더 적절해 보이네요

2023-12-18 06:01 UTC, pho9902 approved these changes

2023-12-19 06:59 UTC, soonki-98 approved these changes

2023-12-19 06:59 UTC, merged