Feat/woo/qyog 162
modern-agile-team/dongurami-front-v2 pull request #87
Opened 2024-05-29 05:35 UTC by pho9902

# Pull Request

## 티켓

[QYOG-162](https://dongurami.atlassian.net/browse/QYOG-162)

## 작업 내용

- 셀렉트박스 디자인시스템 개발

## 스크린샷

![image](https://github.com/modern-agile-team/dongurami-front-v2/assets/83463918/45d2a044-c848-4460-b508-a9026f012f07)

## 테스트

- 스토리북 components/SelectBox 확인

2024-05-31 05:18 UTC, jsj1510 approved these changes

2024-06-10 00:59 UTC, soonki-98 commented
전에 오프라인으로 남긴 리뷰 반영 부탁해요

2024-06-10 03:07 UTC, soonki-98 requested changes
오프라인 리뷰 반영 바람

2024-06-21 14:29 UTC, soonki-98 approved these changes

2024-06-21 14:30 UTC, merged